version: "3.1"
services:
  web:
    image: python:3.7-alpine
    container_name: flask-app
    build: .
    ports:
      - 8080:8080
  db:
    image: mongo:3.5
    container_name: mongo-db
    restart: always
    environment:
      MONGO_INITDB_DATABASE: mongo-db
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1G
