version: "3.1"
services:
  web:
    image: python:3.7-alpine
    container_name: flask-app
    build: .
    ports:
      - 8080:8080
  db:
    image: mysql:5.7
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: mysql-db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1G
